import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import type { Plugin } from "vite";

/**
 * Emits a service worker that precaches exactly what Vite wrote to
 * `dist/client`, and nothing else.
 *
 * Inherited from the design-system R&D bench and extended for a server-backed
 * app: the shell and its assets are precached cache-first, captured media is
 * cached on first view (the files are immutable, so a hit is always correct),
 * and `/api` is never cached — a stale collection served as if it were live is
 * worse than an honest offline banner. The client keeps its own snapshot in
 * localStorage for the offline read.
 */
export function offlineShell(): Plugin {
  const version = new Date().toISOString().slice(0, 16).replace(/[-:T]/g, "");
  return {
    name: "drd:offline-shell",
    apply: "build",
    closeBundle() {
      const outDir = join(process.cwd(), "dist", "client");
      const files: string[] = [];
      const walk = (dir: string) => {
        for (const entry of readdirSync(dir)) {
          const abs = join(dir, entry);
          if (statSync(abs).isDirectory()) walk(abs);
          else files.push("/" + relative(outDir, abs).split(sep).join("/"));
        }
      };
      walk(outDir);
      const precache = files.filter((f) => f !== "/sw.js").concat(["/app"]);
      writeFileSync(join(outDir, "sw.js"), serviceWorkerSource(version, precache));
    },
  };
}

function serviceWorkerSource(version: string, precache: string[]): string {
  return `// generated by vite.config.ts — do not edit
const CACHE = 'drd-${version}';
const MEDIA_CACHE = 'drd-media';
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // 'reload' on every entry: addAll revalidates by default, and anything the
    // page already fetched comes back 304, which makes Cache.add reject and
    // voids the whole precache. Per-entry allSettled for the same reason in
    // reverse — one unreachable file must not cost the other thirty.
    const results = await Promise.allSettled(
      PRECACHE.map((url) => cache.add(new Request(url, { cache: 'reload' })))
    );
    const failed = PRECACHE.filter((_, i) => results[i].status === 'rejected');
    if (failed.length) console.warn('[drd] precache missed', failed);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k !== MEDIA_CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  // Never cache the worker itself: a CacheStorage hit would pin this version
  // forever and no deploy would ever take effect.
  if (url.pathname === '/sw.js') return;

  // The API is the source of truth. Serving it from a cache would hand the
  // user a collection that silently disagrees with the server.
  if (url.pathname.startsWith('/api/')) return;

  // Captured media never changes under its URL — cache on first view so a
  // collection read offline still shows its screenshots.
  if (url.pathname.startsWith('/media/')) {
    event.respondWith((async () => {
      const cache = await caches.open(MEDIA_CACHE);
      const hit = await cache.match(request);
      if (hit) return hit;
      try {
        const response = await fetch(request);
        if (response.ok) cache.put(request, response.clone());
        return response;
      } catch (error) {
        return Response.error();
      }
    })());
    return;
  }

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(request)
        .then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => {
          // Only a navigation may fall back to the shell. Answering a failed
          // font request with HTML is worse than a clean network error.
          if (request.mode === 'navigate') {
            return caches.match('/index.html').then((shell) => shell || Response.error());
          }
          return Response.error();
        });
    })
  );
});
`;
}

export default {
  plugins: [offlineShell()],
  build: { outDir: "dist/client", emptyOutDir: true, target: "es2022", assetsInlineLimit: 0 },
  server: {
    host: "127.0.0.1",
    port: 5177,
    proxy: {
      "/api": "http://127.0.0.1:5178",
      "/media": "http://127.0.0.1:5178",
    },
  },
  preview: { host: "127.0.0.1", port: 4173 },
};
